// <auto-generated />
using System;
using DemoMVC;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoMVC.Migrations
{
    [DbContext(typeof(StockContext))]
    [Migration("20250926141228_AddUsers")]
    partial class AddUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DemoMVC.Entities.Customer", b =>
                {
                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Reference");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Reference = "C001",
                            Email = "alice.durand@example.com",
                            FirstName = "Alice",
                            IsDeleted = false,
                            LastName = "Durand",
                            Phone = "0612345678"
                        },
                        new
                        {
                            Reference = "C002",
                            Email = "thomas.martin@example.com",
                            FirstName = "Thomas",
                            IsDeleted = false,
                            LastName = "Martin",
                            Phone = "0698765432"
                        },
                        new
                        {
                            Reference = "C003",
                            Email = "julie.bernard@example.com",
                            FirstName = "Julie",
                            IsDeleted = false,
                            LastName = "Bernard",
                            Phone = "0711122233"
                        },
                        new
                        {
                            Reference = "C004",
                            Email = "hugo.petit@example.com",
                            FirstName = "Hugo",
                            IsDeleted = false,
                            LastName = "Petit",
                            Phone = "0788889999"
                        },
                        new
                        {
                            Reference = "C005",
                            Email = "emma.robert@example.com",
                            FirstName = "Emma",
                            IsDeleted = false,
                            LastName = "Robert",
                            Phone = "0677001122"
                        },
                        new
                        {
                            Reference = "C006",
                            Email = "lucas.richard@example.com",
                            FirstName = "Lucas",
                            IsDeleted = false,
                            LastName = "Richard",
                            Phone = "0655443322"
                        },
                        new
                        {
                            Reference = "C007",
                            Email = "chloe.moreau@example.com",
                            FirstName = "Chloé",
                            IsDeleted = false,
                            LastName = "Moreau",
                            Phone = "0777001122"
                        },
                        new
                        {
                            Reference = "C008",
                            Email = "nathan.simon@example.com",
                            FirstName = "Nathan",
                            IsDeleted = false,
                            LastName = "Simon",
                            Phone = "0611223344"
                        },
                        new
                        {
                            Reference = "C009",
                            Email = "manon.laurent@example.com",
                            FirstName = "Manon",
                            IsDeleted = false,
                            LastName = "Laurent",
                            Phone = "0666554433"
                        },
                        new
                        {
                            Reference = "C010",
                            Email = "louis.lefebvre@example.com",
                            FirstName = "Louis",
                            IsDeleted = false,
                            LastName = "Lefebvre",
                            Phone = "0622334455"
                        },
                        new
                        {
                            Reference = "C011",
                            Email = "camille.michel@example.com",
                            FirstName = "Camille",
                            IsDeleted = false,
                            LastName = "Michel",
                            Phone = "0688997744"
                        },
                        new
                        {
                            Reference = "C012",
                            Email = "arthur.garcia@example.com",
                            FirstName = "Arthur",
                            IsDeleted = false,
                            LastName = "Garcia",
                            Phone = "0633445566"
                        },
                        new
                        {
                            Reference = "C013",
                            Email = "lea.david@example.com",
                            FirstName = "Léa",
                            IsDeleted = false,
                            LastName = "David",
                            Phone = "0700112233"
                        },
                        new
                        {
                            Reference = "C014",
                            Email = "gabriel.roux@example.com",
                            FirstName = "Gabriel",
                            IsDeleted = false,
                            LastName = "Roux",
                            Phone = "0755667788"
                        },
                        new
                        {
                            Reference = "C015",
                            Email = "sarah.vincent@example.com",
                            FirstName = "Sarah",
                            IsDeleted = false,
                            LastName = "Vincent",
                            Phone = "0766007788"
                        },
                        new
                        {
                            Reference = "C016",
                            Email = "noah.muller@example.com",
                            FirstName = "Noah",
                            IsDeleted = false,
                            LastName = "Muller",
                            Phone = "0799001122"
                        },
                        new
                        {
                            Reference = "C017",
                            Email = "clara.fournier@example.com",
                            FirstName = "Clara",
                            IsDeleted = false,
                            LastName = "Fournier",
                            Phone = "0644556677"
                        },
                        new
                        {
                            Reference = "C018",
                            Email = "ethan.girard@example.com",
                            FirstName = "Ethan",
                            IsDeleted = false,
                            LastName = "Girard",
                            Phone = "0722003344"
                        },
                        new
                        {
                            Reference = "C019",
                            Email = "sophie.andre@example.com",
                            FirstName = "Sophie",
                            IsDeleted = false,
                            LastName = "Andre",
                            Phone = "0677889900"
                        },
                        new
                        {
                            Reference = "C020",
                            Email = "antoine.mercier@example.com",
                            FirstName = "Antoine",
                            IsDeleted = false,
                            LastName = "Mercier",
                            Phone = "0611998877"
                        });
                });

            modelBuilder.Entity("DemoMVC.Entities.Order", b =>
                {
                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerRef")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Reference");

                    b.HasIndex("CustomerRef");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Reference = "O001",
                            CreationDate = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerRef = "C001",
                            OrderStatus = 2,
                            PaymentDate = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPrice = 259.90m
                        },
                        new
                        {
                            Reference = "O002",
                            CreationDate = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerRef = "C003",
                            OrderStatus = 1,
                            TotalPrice = 89.99m
                        },
                        new
                        {
                            Reference = "O003",
                            CreationDate = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerRef = "C002",
                            OrderStatus = 2,
                            PaymentDate = new DateTime(2025, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPrice = 1599.00m
                        },
                        new
                        {
                            Reference = "O004",
                            CreationDate = new DateTime(2025, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerRef = "C005",
                            OrderStatus = 0,
                            TotalPrice = 49.99m
                        },
                        new
                        {
                            Reference = "O005",
                            CreationDate = new DateTime(2025, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerRef = "C004",
                            OrderStatus = 2,
                            PaymentDate = new DateTime(2025, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPrice = 329.90m
                        },
                        new
                        {
                            Reference = "O006",
                            CreationDate = new DateTime(2025, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerRef = "C006",
                            OrderStatus = 1,
                            TotalPrice = 75.00m
                        },
                        new
                        {
                            Reference = "O007",
                            CreationDate = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerRef = "C010",
                            OrderStatus = 2,
                            PaymentDate = new DateTime(2025, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPrice = 1249.00m
                        },
                        new
                        {
                            Reference = "O008",
                            CreationDate = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerRef = "C008",
                            OrderStatus = 0,
                            TotalPrice = 199.00m
                        },
                        new
                        {
                            Reference = "O009",
                            CreationDate = new DateTime(2025, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerRef = "C012",
                            OrderStatus = 3,
                            TotalPrice = 59.99m
                        },
                        new
                        {
                            Reference = "O010",
                            CreationDate = new DateTime(2025, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerRef = "C015",
                            OrderStatus = 2,
                            PaymentDate = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPrice = 899.00m
                        });
                });

            modelBuilder.Entity("DemoMVC.Entities.OrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OrderRef")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductRef")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderRef");

                    b.HasIndex("ProductRef");

                    b.ToTable("OrderLines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderRef = "O001",
                            Price = 89.99m,
                            ProductRef = "P001",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            OrderRef = "O001",
                            Price = 49.99m,
                            ProductRef = "P002",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 3,
                            OrderRef = "O001",
                            Price = 59.00m,
                            ProductRef = "P006",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 4,
                            OrderRef = "O002",
                            Price = 59.99m,
                            ProductRef = "P015",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 5,
                            OrderRef = "O002",
                            Price = 19.90m,
                            ProductRef = "P013",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 6,
                            OrderRef = "O002",
                            Price = 12.90m,
                            ProductRef = "P014",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 7,
                            OrderRef = "O003",
                            Price = 1699.00m,
                            ProductRef = "P020",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 8,
                            OrderRef = "O003",
                            Price = 75.00m,
                            ProductRef = "P007",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 9,
                            OrderRef = "O003",
                            Price = 14.99m,
                            ProductRef = "P009",
                            Quantity = 3
                        },
                        new
                        {
                            Id = 10,
                            OrderRef = "O004",
                            Price = 49.99m,
                            ProductRef = "P002",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 11,
                            OrderRef = "O004",
                            Price = 89.99m,
                            ProductRef = "P001",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 12,
                            OrderRef = "O004",
                            Price = 24.99m,
                            ProductRef = "P010",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 13,
                            OrderRef = "O005",
                            Price = 329.90m,
                            ProductRef = "P004",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 14,
                            OrderRef = "O005",
                            Price = 19.90m,
                            ProductRef = "P013",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 15,
                            OrderRef = "O005",
                            Price = 12.90m,
                            ProductRef = "P014",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 16,
                            OrderRef = "O005",
                            Price = 89.00m,
                            ProductRef = "P011",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 17,
                            OrderRef = "O006",
                            Price = 75.00m,
                            ProductRef = "P007",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 18,
                            OrderRef = "O006",
                            Price = 139.00m,
                            ProductRef = "P008",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 19,
                            OrderRef = "O006",
                            Price = 14.99m,
                            ProductRef = "P009",
                            Quantity = 3
                        },
                        new
                        {
                            Id = 20,
                            OrderRef = "O007",
                            Price = 899.00m,
                            ProductRef = "P019",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 21,
                            OrderRef = "O007",
                            Price = 129.00m,
                            ProductRef = "P016",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 22,
                            OrderRef = "O007",
                            Price = 59.00m,
                            ProductRef = "P006",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 23,
                            OrderRef = "O007",
                            Price = 39.00m,
                            ProductRef = "P012",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 24,
                            OrderRef = "O008",
                            Price = 119.00m,
                            ProductRef = "P005",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 25,
                            OrderRef = "O008",
                            Price = 59.99m,
                            ProductRef = "P015",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 26,
                            OrderRef = "O008",
                            Price = 19.90m,
                            ProductRef = "P013",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 27,
                            OrderRef = "O008",
                            Price = 12.90m,
                            ProductRef = "P014",
                            Quantity = 3
                        },
                        new
                        {
                            Id = 28,
                            OrderRef = "O009",
                            Price = 59.99m,
                            ProductRef = "P015",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 29,
                            OrderRef = "O009",
                            Price = 24.99m,
                            ProductRef = "P010",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 30,
                            OrderRef = "O009",
                            Price = 59.00m,
                            ProductRef = "P006",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 31,
                            OrderRef = "O009",
                            Price = 49.99m,
                            ProductRef = "P002",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 32,
                            OrderRef = "O010",
                            Price = 899.00m,
                            ProductRef = "P019",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 33,
                            OrderRef = "O010",
                            Price = 75.00m,
                            ProductRef = "P007",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 34,
                            OrderRef = "O010",
                            Price = 139.00m,
                            ProductRef = "P008",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 35,
                            OrderRef = "O010",
                            Price = 14.99m,
                            ProductRef = "P009",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 36,
                            OrderRef = "O010",
                            Price = 39.00m,
                            ProductRef = "P012",
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("DemoMVC.Entities.Product", b =>
                {
                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("LastBuyingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Reference");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Reference = "P001",
                            Description = "Clavier mécanique rétroéclairé RGB",
                            IsDeleted = false,
                            LastBuyingPrice = 65.00m,
                            Name = "Clavier mécanique",
                            Price = 89.99m,
                            Quantity = 25
                        },
                        new
                        {
                            Reference = "P002",
                            Description = "Souris sans fil haute précision",
                            IsDeleted = false,
                            LastBuyingPrice = 35.00m,
                            Name = "Souris gaming",
                            Price = 49.99m,
                            Quantity = 40
                        },
                        new
                        {
                            Reference = "P003",
                            Description = "Moniteur Full HD 75Hz",
                            IsDeleted = false,
                            LastBuyingPrice = 120.00m,
                            Name = "Écran 24 pouces",
                            Price = 159.90m,
                            Quantity = 12
                        },
                        new
                        {
                            Reference = "P004",
                            Description = "Moniteur 2K IPS 144Hz",
                            IsDeleted = false,
                            LastBuyingPrice = 250.00m,
                            Name = "Écran 27 pouces",
                            Price = 329.90m,
                            Quantity = 8
                        },
                        new
                        {
                            Reference = "P005",
                            Description = "Casque sans fil avec réduction de bruit",
                            IsDeleted = false,
                            LastBuyingPrice = 90.00m,
                            Name = "Casque audio",
                            Price = 119.00m,
                            Quantity = 15
                        },
                        new
                        {
                            Reference = "P006",
                            Description = "Caméra 1080p avec micro intégré",
                            IsDeleted = false,
                            LastBuyingPrice = 40.00m,
                            Name = "Webcam HD",
                            Price = 59.00m,
                            Quantity = 30
                        },
                        new
                        {
                            Reference = "P007",
                            Description = "SSD NVMe haute performance",
                            IsDeleted = false,
                            LastBuyingPrice = 55.00m,
                            Name = "Disque SSD 500GB",
                            Price = 75.00m,
                            Quantity = 50
                        },
                        new
                        {
                            Reference = "P008",
                            Description = "SSD NVMe PCIe Gen4 rapide",
                            IsDeleted = false,
                            LastBuyingPrice = 110.00m,
                            Name = "Disque SSD 1TB",
                            Price = 139.00m,
                            Quantity = 35
                        },
                        new
                        {
                            Reference = "P009",
                            Description = "Clé USB 3.1 haute vitesse",
                            IsDeleted = false,
                            LastBuyingPrice = 9.00m,
                            Name = "Clé USB 64GB",
                            Price = 14.99m,
                            Quantity = 100
                        },
                        new
                        {
                            Reference = "P010",
                            Description = "Clé USB 3.2 ultra rapide",
                            IsDeleted = false,
                            LastBuyingPrice = 18.00m,
                            Name = "Clé USB 128GB",
                            Price = 24.99m,
                            Quantity = 80
                        },
                        new
                        {
                            Reference = "P011",
                            Description = "Dock USB-C avec HDMI et RJ45",
                            IsDeleted = false,
                            LastBuyingPrice = 65.00m,
                            Name = "Station d’accueil",
                            Price = 89.00m,
                            Quantity = 20
                        },
                        new
                        {
                            Reference = "P012",
                            Description = "Chargeur universel USB-C Power Delivery",
                            IsDeleted = false,
                            LastBuyingPrice = 25.00m,
                            Name = "Chargeur 65W",
                            Price = 39.00m,
                            Quantity = 60
                        },
                        new
                        {
                            Reference = "P013",
                            Description = "Câble HDMI 2.1 compatible 4K/8K",
                            IsDeleted = false,
                            LastBuyingPrice = 10.00m,
                            Name = "Câble HDMI 2m",
                            Price = 19.90m,
                            Quantity = 150
                        },
                        new
                        {
                            Reference = "P014",
                            Description = "Câble USB-C vers USB-C 3.2",
                            IsDeleted = false,
                            LastBuyingPrice = 7.00m,
                            Name = "Câble USB-C 1m",
                            Price = 12.90m,
                            Quantity = 200
                        },
                        new
                        {
                            Reference = "P015",
                            Description = "Enceinte portable étanche IPX7",
                            IsDeleted = false,
                            LastBuyingPrice = 40.00m,
                            Name = "Enceinte Bluetooth",
                            Price = 59.99m,
                            Quantity = 45
                        },
                        new
                        {
                            Reference = "P016",
                            Description = "Imprimante couleur Wi-Fi multifonction",
                            IsDeleted = false,
                            LastBuyingPrice = 95.00m,
                            Name = "Imprimante jet d’encre",
                            Price = 129.00m,
                            Quantity = 10
                        },
                        new
                        {
                            Reference = "P017",
                            Description = "Imprimante laser monochrome rapide",
                            IsDeleted = false,
                            LastBuyingPrice = 150.00m,
                            Name = "Imprimante laser",
                            Price = 189.00m,
                            Quantity = 7
                        },
                        new
                        {
                            Reference = "P018",
                            Description = "Tablette Android 128GB",
                            IsDeleted = false,
                            LastBuyingPrice = 200.00m,
                            Name = "Tablette 10 pouces",
                            Price = 249.00m,
                            Quantity = 18
                        },
                        new
                        {
                            Reference = "P019",
                            Description = "Laptop 15,6'' i5 16GB RAM 512GB SSD",
                            IsDeleted = false,
                            LastBuyingPrice = 750.00m,
                            Name = "Ordinateur portable",
                            Price = 899.00m,
                            Quantity = 5
                        },
                        new
                        {
                            Reference = "P020",
                            Description = "Laptop 17'' i7 RTX 4060",
                            IsDeleted = false,
                            LastBuyingPrice = 1450.00m,
                            Name = "Ordinateur portable gaming",
                            Price = 1699.00m,
                            Quantity = 3
                        });
                });

            modelBuilder.Entity("DemoMVC.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "550e8400-e29b-41d4-a716-446655440000u5einAERS8EItqIy+rH5gVUhekOJY/cfs5aaPtoL0Zm4OqSbAYHhA7xi7nHs3eS5AGsSfQGzhfiF41g/+hQjBg==",
                            UserRole = 0,
                            Username = "Khun"
                        },
                        new
                        {
                            Id = 2,
                            Password = "3f2504e0-4f89-11d3-9a0c-0305e82c3301lPBxNGlo/GMo/wuKODnhTYhppwkSWYlup+uPl9DqOF2+DGqCMhoNeGDIyO9QnxqlPbrob5TvYKYuzpQtn9KRgg==",
                            UserRole = 1,
                            Username = "Yass"
                        },
                        new
                        {
                            Id = 3,
                            Password = "9a3b1c6d-7f9e-4a2f-b8e7-123456789abc7dZfR3gYtqSZsF5uZoO9PjxIfdnvuUNRrsZmy2RzJP5sYQKRPW6Uw7WgPPx1PrIes/dOmiJrnPhZhutrtA6KFA==",
                            UserRole = 2,
                            Username = "Laur"
                        });
                });

            modelBuilder.Entity("DemoMVC.Entities.Order", b =>
                {
                    b.HasOne("DemoMVC.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DemoMVC.Entities.OrderLine", b =>
                {
                    b.HasOne("DemoMVC.Entities.Order", "Order")
                        .WithMany("OrderLines")
                        .HasForeignKey("OrderRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DemoMVC.Entities.Product", "Product")
                        .WithMany("OrderLines")
                        .HasForeignKey("ProductRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DemoMVC.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("DemoMVC.Entities.Order", b =>
                {
                    b.Navigation("OrderLines");
                });

            modelBuilder.Entity("DemoMVC.Entities.Product", b =>
                {
                    b.Navigation("OrderLines");
                });
#pragma warning restore 612, 618
        }
    }
}
